#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
version: '3'

services:

  # ---------------------
  # MySQL service
  # ---------------------
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: "hawkbit"
      MYSQL_USER: "hawkbit"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:?Must set environment variables in .env}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?Must set environment variables in .env}"
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - 3306
    labels:
      NAME: "mysql"

  # ---------------------
  # HawkBit service
  # ---------------------
  hawkbit:
    image: "hawkbit/hawkbit-update-server:latest-mysql"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql:3306/hawkbit",
        "spring.datasource.username": "hawkbit",
        "spring.datasource.password": "${MYSQL_PASSWORD}",
        "hawkbit.dmf.rabbitmq.enabled": false,
        "hawkbit.server.im.users[0].username": "admin",
        "hawkbit.server.im.users[0].password": "${HAWKBIT_ADMIN_PASSWORD:?Must set environment variables in .env}",
        "hawkbit.server.im.users[0].permissions": "ALL",
        "hawkbit.server.im.users[1].username": "device",
        "hawkbit.server.im.users[1].password": "${HAWKBIT_DEVICE_PASSWORD:?Must set environment variables in .env}",
        "hawkbit.server.im.users[1].permissions": "READ_TARGET_SECURITY_TOKEN,CREATE_TARGET",
        "hawkbit.server.ddi.security.authentication.targettoken.enabled": true,
        "hawkbit.controller.pollingTime": "${HAWKBIT_POLLING_TIME:-00:05:00}",
        "spring.servlet.multipart.max-file-size": "${HAWKBIT_MAX_FILE_SIZE:-1024MB}",
        "spring.servlet.multipart.max-request-size": "-1",
        "server.forward-headers-strategy": "NATIVE"
      }'
    restart: always
    volumes:
      - ./hawkbit_artifactrepo:/opt/hawkbit/artifactrepo
    ports:
        - "${HAWKBIT_LISTEN_HOST:-0.0.0.0}:8080:${HAWKBIT_LISTEN_PORT:-8080}"
    labels:
      NAME: "hawkbit"
