#!/bin/sh

PODMAN_ROOT=
PODMAN_LOAD=
PUB_KEY=
if [ -z "$SWUPDATE_USB_SWU" ]; then
	ARCHIVE_DIR=/mnt
else
	ARCHIVE_DIR="${SWUPDATE_USB_SWU%/*}"
	[ -n "$ARCHIVE_DIR" ] || ARCHIVE_DIR=/
fi

[ -z "${CONTAINERS_CONF+x}" ] && \
	[ -e /etc/atmark/containers.conf ] && \
	export CONTAINERS_CONF=/etc/atmark/containers.conf
[ -z "${CONTAINERS_STORAGE_CONF+x}" ] && \
	[ -e /etc/atmark/containers_storage.conf ] && \
	export CONTAINERS_STORAGE_CONF=/etc/atmark/containers_storage.conf
[ -z "${CONTAINERS_REGISTRIES_CONF+x}" ] && \
	[ -e /etc/atmark/containers_registries.conf ] && \
	export CONTAINERS_REGISTRIES_CONF=/etc/atmark/containers_registries.conf

error() {
	printf -- "----------------------------------------------\n" >&2
	printf -- "/!\ %s\n" "$@" >&2
	printf -- "----------------------------------------------\n" >&2
	exit 1
}

warning() {
        case "$SWUPDATE_WARN_FD" in
        4) printf "%s\n" "$@" >&4;;
        *) printf "%s\n" "$@" >&2;;
        esac
}

# info commands duplicated from scripts/common
stdout_info() {
	# this one keeps stdout if unset
	case "$SWUPDATE_INFO_FD" in
	3) "$@" >&3;;
	*) "$@";;
	esac
}

# options:
# FILTER: run grep -vE on filter and only print non-matches
# NOSTDOUT: drop stdout and only consider stderr (for openssl cms-verify)
info_if_not_empty() {
	local output="${TMPDIR:-/var/tmp}/scripts/cmd_output"
	local ret

	if [ -n "$NOSTDOUT" ]; then
		"$@" 2> "$output" >/dev/null
	else
		"$@" > "$output" 2>&1
	fi
	ret=$?

	if [ -n "$FILTER" ]; then
		# can't check for grep error redirecting file as it returns
		# non-zero if no match... hopefully mv will fail then?
		grep -vE "$FILTER" < "$output" > "$output.filter"
		if ! mv "$output.filter" "$output"; then
			echo "Could not filter '$*' output" >&2
			ret=1
		fi
	fi

	if [ -s "$output" ]; then
		stdout_info echo "Command '$*' output:"
		stdout_info cat "$output"
	fi
	rm -f "$output"
	return "$ret"
}

podman_info() {
	info_if_not_empty command podman "$@"
}

usage() {
	echo "Usage: $0 [options] [-l [archive...]|uri...]"
	echo
	echo "Helper to update containers"
	echo
	echo "  -l    Instead of podman pull, use podman load to install update"
	echo "        In this case if no argument is provided tries to load from stdin"
	echo
	echo "Options:"
	echo " --storage <path> Path to podman storage to update"
	echo " --pubkey <key>   Public key used to verify signed image (load with parameter only)"
	echo "                  Setting to empty string disables the check"
}

podman_pull() {
	local uri="$1"
	local old_image new_image

	podman_info pull --root "$PODMAN_ROOT" \
			--storage-opt additionalimagestore="" -q "$uri" \
		|| error "Could not pull $image"
}

check_sig() {
	local file="$1"

	FILTER="Verification successful" NOSTDOUT=1 info_if_not_empty \
		openssl cms -verify -inform DER -in "$file.sig" \
				-content "$file" -nosmimecap -no_check_time \
				-binary -CAfile "$PUB_KEY" ||
			error "Signature verification failed"
}

podman_load() {
	local archive

	if [ $# -eq 0 ]; then
		podman_info load --root "$PODMAN_ROOT" \
			--storage-opt additionalimagestore=""
	else for archive; do
		case "$archive" in
		/*) ;;
		*) archive="$ARCHIVE_DIR/$archive";;
		esac
		if [ -n "$PUB_KEY" ]; then
			check_sig "$archive"
		fi
		podman_info load --root "$PODMAN_ROOT" \
			--storage-opt additionalimagestore="" \
			-i "$archive"
	done fi
}

update_containers() {
	local uri

	# find which db to use: we prefer persistent development storage
	# over readonly one as images in ro storage won't be visible
	if [ -z "$PODMAN_ROOT" ]; then
		if grep -q 'containers/storage_readonly' /etc/containers/storage.conf; then
			PODMAN_ROOT=/target/var/lib/containers/storage_readonly
		else
			# note we don't use /target bind: they're identical, but bolt_sate.db
			# has the canonical path
			PODMAN_ROOT=/var/lib/containers/storage
			warning "Updating images on development storage, do not use this mode for production!" \
			       "(Old images are never removed, not safe on power loss...)"
		fi
		mountpoint -q "$PODMAN_ROOT" \
			|| error "Trying to use $PODMAN_ROOT which is not mounted"
	fi

	# cleanup podman silly location-binding db before/after using directory.
	[ -z "$(podman ps --root "$PODMAN_ROOT" -qa)" ] \
		|| error "podman state not clean"
	rm -f "$PODMAN_ROOT/libpod/bolt_state.db"

	if [ -n "$PODMAN_LOAD" ]; then
		podman_load "$@"
	else
		for uri do
			podman_pull "$uri"
		done
	fi

	# cleanup again afterwards for whoever comes next
	rm -f "$PODMAN_ROOT/libpod/bolt_state.db"
}

[ $# -lt 1 ] && usage && exit 1

while [ $# -ge 1 ]; do
	case "$1" in
	"-l")
		PODMAN_LOAD=yes
		shift
		;;
	"--pubkey")
		[ $# -ge 2 ] || error "$1 needs an argument"
		PUB_KEY="$2"
		shift 2
		;;
	"--storage")
		[ $# -ge 2 ] || error "$1 needs an argument"
		PODMAN_ROOT="$2"
		shift 2
		;;
	"--")
		shift
		break
		;;
	"-h"|"--help"|"-"*)
		usage
		exit 0
		;;
	*)
		break
		;;
	esac
done

update_containers "$@"

